version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - "/usr/projects/mysql_data:/var/lib/mysql" 
    environment:
     MYSQL_ROOT_PASSWORD: example_pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_PORT: db
      PMA_USER: example_user
      PMA_PASSWORD: example_pass

  services:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ".:/usr/projects/current"
      - "./media:/usr/projects/current/media"
    depends_on:
      - db