# Generated by Django 2.2.1 on 2020-10-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenderCSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_property', models.CharField(max_length=255, verbose_name='Свойство CSS')),
                ('css_value', models.CharField(max_length=255, verbose_name='Значение свойства CSS')),
            ],
            options={
                'verbose_name': 'CSS свойство',
                'verbose_name_plural': 'CSS свойства',
            },
        ),
        migrations.CreateModel(
            name='RenderClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование класса отрисовки')),
                ('styles', models.ManyToManyField(to='render.RenderCSS', verbose_name='Стили класса')),
            ],
            options={
                'verbose_name': 'Класс отрисовки',
                'verbose_name_plural': 'Классы отрисовки',
            },
        ),
    ]
